#!/usr/bin/env bash
# install.sh — interactive installer for the Orthodox calendar files (BSB
# `calendar(1)` command: macOS / FreeBSD / OpenBSD).
#
# Asks three questions:
#   1. Which calendar channels to install.
#   2. Whether to bold the main commemoration.
#   3. Where to install (defaults to ~/.calendar).
#
# Non-interactive shortcut:  ./install.sh --all [--bold] [DIR]

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# Channel descriptions (keyed by short tag).
TAGS=(saints fasts readings vespers summary)
desc_for() {
    case "$1" in
        saints)   echo "Daily saints & feast commemorations" ;;
        fasts)    echo "Fasting discipline (glyph + text)" ;;
        readings) echo "Daily Scriptural readings" ;;
        vespers)  echo "Great Feast Vigil Old-Testament readings" ;;
        summary)  echo "One-line digest (feast + fast + Gospel)" ;;
        *)        echo "" ;;
    esac
}

# ---------------------------------------------------------------------------
# Argument pre-scan (allows skipping prompts)
# ---------------------------------------------------------------------------
WANT_ALL=0
BOLD=0
ARG_DIR=""
for a in "$@"; do
    case "$a" in
        --all)  WANT_ALL=1 ;;
        --bold) BOLD=1 ;;
        *)      ARG_DIR="$a" ;;
    esac
done

echo "Orthodox Calendar installer"
echo "==========================="
echo

# 1. Which calendars?
SELECTED=()
if [ "$WANT_ALL" = 1 ]; then
    SELECTED=("${TAGS[@]}")
else
    echo "Select which calendars to install:"
    echo "  (all)        all of the below"
    for t in "${TAGS[@]}"; do
        printf '  %-12s — %s\n' "$t" "$(desc_for "$t")"
    done
    printf '\nTags (comma-separated, or "all" [default]): '
    read -r choice
    choice="$(echo "$choice" | tr -d '[:space:]' | tr 'A-Z' 'a-z')"
    if [ -z "$choice" ] || [ "$choice" = "all" ]; then
        SELECTED=("${TAGS[@]}")
    else
        IFS=',' read -r -a SELECTED <<< "$choice"
    fi
fi

# 2. Bold? (skip if --bold already set by flag)
if [ "$BOLD" = 0 ] && [ -z "$ARG_DIR" ]; then
    printf '\nBold the main commemoration? [y/N] '
    read -r b
    case "$b" in
        y|Y|yes|YES) BOLD=1 ;;
        *) BOLD=0 ;;
    esac
fi

# 3. Directory (skip if given as an argument)
if [ -n "$ARG_DIR" ]; then
    CAL_DIR="$ARG_DIR"
else
    printf 'Calendar directory [%s]: ' "$HOME/.calendar"
    read -r CAL_DIR
    CAL_DIR="${CAL_DIR:-$HOME/.calendar}"
fi

mkdir -p "$CAL_DIR"

echo
echo "Installing to $CAL_DIR ..."

INSTALLED=0
for t in "${SELECTED[@]}"; do
    f="calendar.$t"
    [ -f "$REPO_DIR/$f" ] || { echo "  MISSING $f (run the generator first)"; continue; }
    if [ "$BOLD" = 1 ] && [ "$f" = "calendar.saints" ]; then
        awk -F '\t' '
            /^\t/   { print; next }
            /^\/\// { print; next }
            NF >= 2 { printf "%s\t\033[1m%s\033[0m\n", $1, $2; next }
            { print }
        ' "$REPO_DIR/$f" > "$CAL_DIR/$f"
        echo "  installed $f (bold)"
    else
        cp "$REPO_DIR/$f" "$CAL_DIR/$f"
        echo "  installed $f"
    fi
    INSTALLED=$((INSTALLED+1))
done

# Master .orthodox that includes only the selected channels.
{
    echo "// Orthodox Calendar — master (generated by install.sh)"
    for t in "${SELECTED[@]}"; do
        echo "#include <calendar.$t>"
    done
    echo
} > "$CAL_DIR/calendar.orthodox"

# Wire up the user's own master file (the one `calendar` reads).
MASTER="$CAL_DIR/calendar"
if [ ! -f "$MASTER" ]; then
    printf '#include <calendar.orthodox>\n' > "$MASTER"
    echo "  created $MASTER"
else
    grep -q 'calendar.orthodox' "$MASTER" || printf '\n#include <calendar.orthodox>\n' >> "$MASTER"
    echo "  $MASTER ready"
fi

echo
echo "Done. Try it:"
echo "  calendar                     # today"
echo "  calendar -A 7                # next 7 days"
[ "$BOLD" = 1 ] && echo "  (bold enabled)"
