#!/usr/bin/env bash
# install.sh — interactive installer for the Orthodox calendar files (BSB
# `calendar(1)` command: macOS / FreeBSD / OpenBSD).
#
# Flow (uses `gum` for the pickers):
#   1. Summary  vs  Detailed
#   2. (Detailed) which channels — space to toggle, Enter to confirm
#   3. Bold the main commemoration?  (gum confirm)
#   4. Install directory
#
# Non-interactive shortcut:  ./install.sh --all [--bold] [DIR]

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---------------------------------------------------------------------------
# Argument pre-scan (allows skipping prompts)
# ---------------------------------------------------------------------------
WANT_ALL=0
BOLD=0
ARG_DIR=""
for a in "$@"; do
    case "$a" in
        --all)  WANT_ALL=1 ;;
        --bold) BOLD=1 ;;
        *)      ARG_DIR="$a" ;;
    esac
done

desc_for() {
    case "$1" in
        saints)   echo "Daily saints & feast commemorations" ;;
        fasts)    echo "Fasting discipline (glyph + text)" ;;
        readings) echo "Daily Scriptural readings" ;;
        vespers)  echo "Great Feast Vigil Old-Testament readings" ;;
    esac
}

# ---------------------------------------------------------------------------
# Stage 1 — summary vs detailed
# ---------------------------------------------------------------------------
MODE=""
if [ "$WANT_ALL" = 1 ]; then
    MODE="detailed"
    SELECTED=(saints fasts readings vespers)
elif command -v gum >/dev/null 2>&1; then
    MODE="$(gum choose --height 4 'Summary — one-line digest' 'Detailed — full channels' 2>/dev/null | sed 's/ .*//' | tr 'A-Z' 'a-z')"
else
    printf 'Summary [S] or Detailed [D]? [D] '
    read -r m
    MODE="$(echo "${m:-d}" | tr 'A-Z' 'a-z')"
    MODE="${MODE:0:1}"
    [ "$MODE" = "s" ] && MODE="summary" || MODE="detailed"
fi

# ---------------------------------------------------------------------------
# Stage 2 — channel picker (detailed only)
# ---------------------------------------------------------------------------
# SELECTED may already be set by --all (stage 1); reset only when unset.
if [ "$MODE" = "summary" ]; then
    SELECTED=(summary)
elif [ -z "${SELECTED[*]+x}" ]; then
        if command -v gum >/dev/null 2>&1; then
            SEL="$(gum choose --no-limit \
                --header 'Select channels (space to toggle, enter to confirm)' \
                'saints — Daily saints & feast commemorations' \
                'fasts — Fasting discipline' \
                'readings — Daily Scriptural readings' \
                'vespers — Great Feast Vigil OT readings' 2>/dev/null)"
            SELECTED=()
            while IFS= read -r s; do
                [ -n "$s" ] && SELECTED+=("${s%% *}")
            done <<< "$SEL"
            [ ${#SELECTED[@]} -gt 0 ] || SELECTED=(saints fasts readings vespers)
        else
            SELECTED=(saints fasts readings vespers)
        fi
fi

# ---------------------------------------------------------------------------
# Stage 3 — bold
# ---------------------------------------------------------------------------
if [ "$BOLD" = 0 ] && [ -z "$ARG_DIR" ]; then
    if command -v gum >/dev/null 2>&1; then
        gum confirm 'Bold the main commemoration?' && BOLD=1 || BOLD=0
    else
        printf 'Bold the main commemoration? [y/N] '
        read -r b; case "$b" in y|Y|yes|YES) BOLD=1;; *) BOLD=0;; esac
    fi
fi
# ---------------------------------------------------------------------------
# Stage 4 — directory
# ---------------------------------------------------------------------------
if [ -n "$ARG_DIR" ]; then
    CAL_DIR="$ARG_DIR"
elif command -v gum >/dev/null 2>&1; then
    CAL_DIR="$(gum input --value "$HOME/.calendar" --placeholder 'Calendar directory' 2>/dev/null)"
    CAL_DIR="${CAL_DIR:-$HOME/.calendar}"
else
    printf 'Calendar directory [%s]: ' "$HOME/.calendar"
    read -r CAL_DIR
    CAL_DIR="${CAL_DIR:-$HOME/.calendar}"
fi

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
mkdir -p "$CAL_DIR"
echo
echo "Installing to $CAL_DIR ..."

for t in "${SELECTED[@]}"; do
    f="calendar.$t"
    [ -f "$REPO_DIR/$f" ] || { echo "  MISSING $f (run the generator first)"; continue; }
    if [ "$BOLD" = 1 ] && [ "$f" = "calendar.saints" ]; then
        awk -F '\t' '
            /^\t/   { print; next }
            /^\/\// { print; next }
            NF >= 2 { printf "%s\t\033[1m%s\033[0m\n", $1, $2; next }
            { print }
        ' "$REPO_DIR/$f" > "$CAL_DIR/$f"
        echo "  installed $f (bold)"
    else
        cp "$REPO_DIR/$f" "$CAL_DIR/$f"
        echo "  installed $f"
    fi
done

# Master .orthodox includes the selected channels.
{
    echo "// Orthodox Calendar — master (generated by install.sh)"
    for t in "${SELECTED[@]}"; do
        echo "#include <calendar.$t>"
    done
    echo
} > "$CAL_DIR/calendar.orthodox"

# Wire up the user's own master file (the one `calendar` reads).
MASTER="$CAL_DIR/calendar"
if [ ! -f "$MASTER" ]; then
    printf '#include <calendar.orthodox>\n' > "$MASTER"
    echo "  created $MASTER"
else
    grep -q 'calendar.orthodox' "$MASTER" || printf '\n#include <calendar.orthodox>\n' >> "$MASTER"
    echo "  $MASTER ready"
fi

echo
echo "Done. Try it:"
echo "  calendar                     # today"
echo "  calendar -A 7                # next 7 days"
[ "$BOLD" = 1 ] && echo "  (bold enabled)"
